abnormalbrain/bevy_particle_systems

src/components.rs, src/systems.rs
**Changes**
- Adds the `despawn_on_finish` field to `ParticleSystem`, which defaults to `false`.
- Only calls `despawn()` on the entity if the `despawn_on_finish` parameter is true, otherwise, simply removes the `Playing` component.
=> Make despawning on system finish optional

src/systems.rs
If the base sprite does not start with the initial scale and color that matches the system, particles may flash one frame of the full sized / incorrectly colored sprite before being corrected.
The modifier systems for particles do not run until the frame after spawn and these parameters are not correctly set during spawning.
Set the sprite color and scale based on the particle system values at the initial (`0.0`) lifetime.
=> Set particle scale and color correctly on spawn

.gitignore, src/systems.rs
Previously the emitter shape range was emitting particles in [`emitter_shape`, `emitter_shape`+`emitter_angle`] range. Causing one edge of the cone to be at the emitter angle.
Instead, we should make the emitter angle be the center of the cone.
=> Center emitter shape on the angle

src/systems.rs
**Problem**
Currently when the spawn rate is zero, a particle system spawner will still spawn 1 particle per second.
**Solution**
Check the spawn rate being zero before doing the spawn count adjustment.
=> Correctly handle spawn rate of zero

src/components.rs
Closes #13 
@darthdeus correctly pointed out that the docs for `emitter_angle` don't match up with the behavior. This corrects the docs to match how the angle is actually interpreted.
=> Update docs for emitter angle to indcate correct default directions

.github/workflows/rust.yml, Cargo.toml, examples/basic.rs, examples/local_space.rs, examples/time_scaling.rs, src/components.rs, src/lib.rs, src/systems.rs
Changes:
- Updates dependencies to Bevy `0.9`
- Removes `TimeScale` in favor of Bevy's global time scaling.
- Updates required rust version to `1.65.0` as Bevy does not work otherwise.
- Use `spawn` instead of `spawn_bundle`
- Compatibility tweaks to examples and docs.
Closes #12 
Thanks to @LarsDu for their previous attempt at this upgrade while it was still in dev and mapping out most of the necessary changes!
=> Upgrade bevy 0.9

Cargo.toml, src/components.rs, src/lib.rs, src/values.rs
This makes it possible for tools like bevy-inspector-egui to show an editor for `ParticleSystem`s.
~~Added it as a default feature so it can be disabled if not needed.~~
=> Add bevy_reflect support

src/components.rs, src/systems.rs
Introduces the `despawn_particles_with_system` field on the `ParticleSystem` which determines particle behavior when the system no longer exists. 
This fixes #20 which was introduced in #17 in the upgrade to Bevy 0.9.
In order to facilitate the particles finishing out their lifetime correctly without the system, more fields that vary over time are copied to the particle itself on spawn, so that a lookup of the spawning `ParticleSystem` is not necessary. 
---
Closes #20
=> Adds despawn_particles_with_system setting and fixes despawn behavior

examples/basic.rs, examples/local_space.rs, examples/time_scaling.rs, src/components.rs, src/lib.rs, src/systems.rs, src/values.rs
PR to be able to handle sprites that come from texture atlas.
My use-case is that all my image assets are stored in a texture atlas, so I need this change to be able to use the library.
I think that it would be interesting to let users have a particle sprite-sheet and the particles randomly use a sprite from the sprite sheet.
This PR is unpolished, I just opened it to see if it's a good idea for you.
If so, I would probably add an SpriteEnum to have 2 mutually exclusive options (Sprite or TextureAtlasSprite)
=> Add texture atlas sprites

src/components.rs, src/systems.rs
The sprites I use are of a given size, but in my game I like to use `transform.scale` to set the exact size of an entity, not to just scale it up or down.
Hence, I usually manually scale all sprites to `Vec2(1.0, 1.0)`, so that the `transform.scale` is the final size of my object.
I think it would be useful to let users have this option. Another way they could do it is to load the particule image directly, compute it's size, and change the `scale` themselves accordingly, but it's somewhat of a hassle compared to just setting the `custom_size` to `(1.0, 1.0)`
=> Add option to rescale sprites

src/components.rs, src/lib.rs, src/systems.rs
I wanted to create some systems in my game that manually overrode the particle `Transform` component.
For that I need to be able to order my systems to run after the `particle_transform` update; I added some SystemLabels to that effect.
=> Add system labels

assets/projectiles.png, examples/local_space.rs, examples/texture_atlas.rs, src/lib.rs, src/plugin.rs, src/systems.rs
Adds a second system to look for particles that use a `TextureAtlasSprite` for color changes. 
Closes #29
=> Fix particle color gradients when using texture atlas particles

src/components.rs, src/systems.rs
Swaps the `distance` call for `distance_squared` to avoid doing square roots for every pixel and improve computation performance.
=> Use distance_squared to compare particle distance

examples/directional.rs, examples/local_space.rs, examples/shape_emitter.rs, examples/time_scaling.rs, src/components.rs, src/systems.rs, src/values.rs
I quickly threw this together for a project of mine, and thought I could as well ask if this is something that could be integrated into the upstream library.
I ran into a situation where I needed particles to be emitted from a line (think Clouds in the background e.g) and found no easy way to do this with this library, so I bundled the three `spawn_radius`, `emitter_shape` and `emitter_angle` properties of the `ParticleSystem` together into an enum `EmitterShape::CircleSegment`. Another variant of this enum is `EmitterShape::Line` which has similar fields that describe a line with a given length - possibly at an angle. 
This enum has an impl with the `sample` function, which returns a random point on the shape of the emitter, which gets used by the `particle_spawner` system to determine …
=> Create enum EmitterShape to allow for emitters other than circles

Cargo.toml, src/components.rs, src/systems.rs, src/values.rs
Adds state tracking to particle gradients, which allows gradients with more than two points to reduce iterations substantially.
For the `basic` demo, this reduced time computing particle color by about 33%.
The inlining of `lerp` made transform computations quite about 22% faster in the same test.
=> Optimize gradients and transforms

src/values.rs
This allows:
emitter_shape: EmitterShape::CircleSegment {
radius: (0.0..0.5).into(),
opening_angle: 0.5,
direction_angle: PI * 3. / 2.,
},
=> Implement `From<Range<f32>>` for `JitteredValue`

README.md, examples/directional.rs, examples/local_space.rs, examples/shape_emitter.rs, examples/time_scaling.rs, src/components.rs, src/values.rs
Changes emitter shapes to use an inner struct to define properties, so that defaults can be used. Also defines a few convenience functions for creating emitter shapes, and adds `Default` to `EmitterShape` itself.
Closes #36
=> [Breaking Change] Make emitter shapes easier to construct

Cargo.toml, src/values.rs
I made a mistake when implementing this initially.
Now the following behave more or less the same:
```rust
initial_speed: (0.0..100.0).into(),
initial_speed: JitteredValue::jittered(0.0, 0.0..100.0),
initial_speed: JitteredValue::jittered(50.0, -50.0..50.0),
```
=> Fix `JitteredValue::centered_range`

examples/oneshot.rs, src/components.rs
Sometimes it's useful with fire-and-forget style particle systems. This adds some convenience to make them, and and example that uses it.
=> Add `ParticleSystem::oneshot` and example

src/components.rs, src/systems.rs
Mirrors implementation of `initial_rotation` and `initial_speed`
=> Add support for jittered initial scale

src/values.rs
It's sometimes useful to just specify the end or start of a curve, without having to duplicate the same value twice.
E.g.
```rust
Curve::new(vec![
CurvePoint::new(1.0, 0.5),
CurvePoint::new(0.0, 1.0),
]);
```
Is equivalent to:
```rust
Curve::new(vec![
CurvePoint::new(1.0, 0.0),
CurvePoint::new(1.0, 0.5),
CurvePoint::new(0.0, 1.0),
]);
```
=> Clamp curves to first/last value

src/lib.rs, src/systems.rs
- Removed some redundant code from a system that was setting both the color of the sprite and the index of the texture atlas, which is no longer necessary after `SpriteSheetBundle` was deprecated. `TextureAtlas` and `Sprite` components are now independent so we can update `Sprite` on one system and the `TextureAtlas` index on the other.
- Refactored `particle_spawner` code to reduce duplication. It should be now clearer that the difference between `ParticleSpace` lies in how the entity hierarchy is built. I feel like this could be simplified a bit more, but I didn't bother fighting against multiple mut borrow issues of `Commands` right now.
- Fixed a small typo in a comment.
=> Refactor `particle_spawner` system
